name: example
version: 1.0.0
description: A new Jetleaf project.
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  jetleaf: ^1.2.1
  jetleaf_scheduling: ^1.1.5
  jetleaf_resource: ^1.1.5
  jetleaf_web: ^1.11.3
  jetleaf_validation: ^1.1.5
  jetleaf_retry: ^1.1.5
  jetleaf_data: ^1.1.3
  build_runner: ^2.10.1

dev_dependencies:
  jetleaf_devtool: ^1.1.5